"""Add Phone Number

Revision ID: cae6cef090a6
Revises: e06cb2c8e052
Create Date: 2023-07-03 14:09:23.762316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae6cef090a6'
down_revision = 'e06cb2c8e052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_Column('users', 'phone_number')
    pass
    # ### end Alembic commands ###
